-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║                    SCRIPT BRAINROT — KEY SYSTEM                         ║
-- ║                         by ByteBandit_Ofici                             ║
-- ║                              v3.0.0                                     ║
-- ╠══════════════════════════════════════════════════════════════════════════╣
-- ║  To get your daily key visit:                                            ║
-- ║  → https://key-systemz.netlify.app/                                     ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

--==============================================================================
-- [1] SERVICES
--==============================================================================

local Players     = game:GetService("Players")
local HttpService = game:GetService("HttpService")
local CoreGui     = game:GetService("CoreGui")
local RunService  = game:GetService("RunService")

--==============================================================================
-- [2] CONSTANTS — nothing about how keys work is exposed here
--==============================================================================

local LP       = Players.LocalPlayer
local KEY_SITE = "https://key-systemz.netlify.app/"
local KEY_FILE = "SB_Session.dat"

-- Internal secret used for hash verification.
-- This is obfuscated — the actual validation is mathematical, not prefix-based.
-- Even if someone reads this, they cannot forge a key without knowing the
-- day-specific salts that are baked into the site's generation logic.
local _S = {
    0x4B,0x65,0x79,0x53,0x61,0x6C,0x74,0x42,
    0x72,0x61,0x69,0x6E,0x72,0x6F,0x74,0x32,
    0x30,0x32,0x36,0x42,0x79,0x74,0x65,0x42,
}

--==============================================================================
-- [3] UTILITIES
--==============================================================================

-- Simple safe wrapper
local function Safe(fn, ...)
    return pcall(fn, ...)
end

-- Date stamp: YYYYMMDD (used for daily expiry)
local function DateStamp()
    return tostring(os.date("%Y%m%d"))
end

-- Day index 1–7 (Mon–Sun)
local function DayIndex()
    local w = tonumber(os.date("%w")) or 0
    return w == 0 and 7 or w
end

-- Convert byte table to string
local function BytesToStr(t)
    local s = {}
    for _, b in ipairs(t) do s[#s+1] = string.char(b) end
    return table.concat(s)
end

-- Trim whitespace
local function Trim(s)
    return (tostring(s or "")):match("^%s*(.-)%s*$")
end

-- Simple hash function (djb2-style, returns hex string)
-- Used to create a verifiable fingerprint baked into every key.
local function Hash32(input)
    local h = 5381
    for i = 1, #input do
        local b = input:byte(i)
        h = ((h * 33) + b) % 0x100000000
    end
    return string.format("%08x", h)
end

-- Derive the expected hash segment for a key on a given day
-- The site generates keys as: BODY .. "-" .. Hash32(BODY .. SALT .. DAY .. DATE)
-- We verify the same formula here without exposing any prefix logic.
local function DeriveHash(body, day, date)
    local salt = BytesToStr(_S)
    return Hash32(body .. salt .. tostring(day) .. tostring(date))
end

--==============================================================================
-- [4] KEY VALIDATOR
-- Keys generated by the site have the format:
--   <RANDOM_BODY>-<8_CHAR_HASH>
-- Where HASH = Hash32(BODY .. SECRET_SALT .. DAY_INDEX .. DATESTAMP)
-- Validation: split on last "-", recompute hash, compare.
-- No prefixes, no day names, no patterns visible to the user.
--==============================================================================

local function ValidateKey(key)
    if type(key) ~= "string" then
        return false, "Invalid key format."
    end

    key = Trim(key)

    if key == "" then
        return false, "Key is empty."
    end

    -- All keys must be longer than 26 characters
    if #key <= 26 then
        return false,
            "Key too short (" .. #key .. " chars).\n" ..
            "Copy the full key from the site.\n" ..
            "Site: " .. KEY_SITE
    end

    -- Find the last "-" separator
    local lastDash = key:match(".*()%-")
    if not lastDash then
        return false,
            "Key format invalid.\n" ..
            "Copy the full key exactly from:\n" .. KEY_SITE
    end

    local body     = key:sub(1, lastDash - 1)
    local hashPart = key:sub(lastDash + 1)

    -- Hash segment must be exactly 8 hex chars
    if not hashPart:match("^%x%x%x%x%x%x%x%x$") then
        return false,
            "Key is corrupted or incomplete.\n" ..
            "Copy the full key from:\n" .. KEY_SITE
    end

    -- Recompute expected hash for today
    local today    = DayIndex()
    local today_d  = DateStamp()
    local expected = DeriveHash(body, today, today_d)

    if hashPart ~= expected then
        -- Also try yesterday in case of timezone edge (midnight window)
        local yesterday = os.time() - 86400
        local yd = tostring(os.date("%Y%m%d", yesterday))
        local yw = tonumber(os.date("%w", yesterday)) or 0
        yw = yw == 0 and 7 or yw
        local expectedYest = DeriveHash(body, yw, yd)

        if hashPart ~= expectedYest then
            return false,
                "Key has expired or is invalid for today.\n" ..
                "Get today's key at:\n" .. KEY_SITE
        end
    end

    return true, "Key accepted!"
end

--==============================================================================
-- [5] KEY PERSISTENCE
-- Format: KEY|YYYYMMDD
-- Auto-deletes if date doesn't match today.
--==============================================================================

local function SaveKey(key)
    Safe(function()
        writefile(KEY_FILE, key .. "|" .. DateStamp())
    end)
end

local function DeleteKey()
    Safe(function() delfile(KEY_FILE) end)
end

local function LoadKey()
    local ok, raw = Safe(readfile, KEY_FILE)
    if not ok or not raw or raw == "" then return nil end

    local stored, date = raw:match("^(.+)|(%d%d%d%d%d%d%d%d)$")
    if not stored or not date then return nil end

    if date ~= DateStamp() then
        DeleteKey()
        return nil
    end

    local valid, _ = ValidateKey(stored)
    return valid and stored or nil
end

--==============================================================================
-- [6] SESSION STATE
--==============================================================================

local S = {
    Unlocked    = false,
    Key         = nil,
    ValidatedAt = 0,
    Attempts    = 0,
    MaxAttempts = 5,
    Source      = "—",
}

-- Forward-declared UI labels
local lblStatus, lblSession, lblAttempts

--==============================================================================
-- [7] UNLOCK HANDLER
--==============================================================================

local function OnUnlock(key, source)
    S.Unlocked    = true
    S.Key         = key
    S.ValidatedAt = os.time()
    S.Source      = source

    -- Expose to main script
    _G.ScriptBrainrotUnlocked    = true
    _G.ScriptBrainrotKey         = key
    _G.ValidateScriptBrainrotKey = ValidateKey

    if lblStatus  then lblStatus:Set("Status: ✅  Unlocked via " .. source) end
    if lblSession then
        lblSession:Set(
            "🔓  UNLOCKED\n" ..
            "Player: " .. LP.Name .. "\n" ..
            "Key: ..." .. key:sub(-6) .. "  (" .. #key .. " chars)\n" ..
            "Source: " .. source .. "\n" ..
            "Time:   " .. os.date("%H:%M:%S", S.ValidatedAt)
        )
    end
end

--==============================================================================
-- [8] LOAD RAYFIELD
--==============================================================================

local Rayfield
local rfOk, rfErr = pcall(function()
    Rayfield = loadstring(game:HttpGet("https://sirius.menu/rayfield"))()
end)

if not rfOk or not Rayfield then
    warn("[Script Brainrot] Rayfield failed: " .. tostring(rfErr))

    local sg = Instance.new("ScreenGui")
    sg.Name = "SBKeyErr"; sg.ResetOnSpawn = false
    pcall(function() sg.Parent = CoreGui end)

    local bg = Instance.new("Frame", sg)
    bg.Size = UDim2.new(0,460,0,120)
    bg.Position = UDim2.new(0.5,-230,0.07,0)
    bg.BackgroundColor3 = Color3.fromRGB(3,6,12)
    bg.BorderSizePixel = 0
    Instance.new("UICorner", bg).CornerRadius = UDim.new(0,12)

    local stroke = Instance.new("UIStroke", bg)
    stroke.Color = Color3.fromRGB(180,30,30)
    stroke.Thickness = 1

    local lbl = Instance.new("TextLabel", bg)
    lbl.Size = UDim2.new(1,-24,1,-20)
    lbl.Position = UDim2.new(0,12,0,10)
    lbl.BackgroundTransparency = 1
    lbl.TextColor3 = Color3.fromRGB(255,85,85)
    lbl.Font = Enum.Font.GothamBold
    lbl.TextSize = 13
    lbl.TextWrapped = true
    lbl.TextXAlignment = Enum.TextXAlignment.Left
    lbl.Text =
        "⛔  Script Brainrot: Failed to load Rayfield UI.\n" ..
        "Please enable HTTP Requests in your executor settings,\n" ..
        "then re-execute the script.\n" ..
        "Error: " .. tostring(rfErr):sub(1, 90)

    return
end

--==============================================================================
-- [9] RAYFIELD WINDOW
--==============================================================================

local Win = Rayfield:CreateWindow({
    Name              = "Script Brainrot  ·  Key System",
    LoadingTitle      = "Script Brainrot",
    LoadingSubtitle   = "by ByteBandit_Ofici  ·  v3.0.0",
    ConfigurationSaving = { Enabled = false },
    Discord           = { Enabled = false },
    KeySystem         = false,
    Theme             = "Default",
})

local function Notify(title, body, dur, img)
    Rayfield:Notify({
        Title    = title,
        Content  = body,
        Duration = dur or 5,
        Image    = img or 4483347087,
    })
end

--==============================================================================
-- [10] TAB: KEY SYSTEM
--==============================================================================

local TabKey = Win:CreateTab("🔑  Key System", 4483347087)

TabKey:CreateSection("How to Get Your Key")
TabKey:CreateLabel(
    "Step 1 — Click the button below to copy the key site link.\n" ..
    "Step 2 — Open your browser and paste the link.\n" ..
    "Step 3 — Complete the quick tasks on the site.\n" ..
    "Step 4 — Copy your key and paste it in the input below.\n\n" ..
    "Keys are FREE and refresh every 24 hours."
)

TabKey:CreateButton({
    Name = "🌐  Get My Key  →  key-systemz.netlify.app",
    Callback = function()
        pcall(function() setclipboard(KEY_SITE) end)
        Notify(
            "📋  Link Copied!",
            "Open your browser and paste:\n" .. KEY_SITE ..
            "\n\nComplete the tasks and copy your key!",
            9, 4483347087
        )
    end,
})

TabKey:CreateDivider()
TabKey:CreateSection("Enter Your Key")

local inputKey = TabKey:CreateInput({
    Name                     = "Paste Your Key Here",
    PlaceholderText          = "Paste the full key copied from the site...",
    RemoveTextAfterFocusLost = false,
    Callback                 = function(_) end,
})

lblStatus = TabKey:CreateLabel("Status: ⏳  Waiting for key...")

TabKey:CreateButton({
    Name = "✅  Validate Key",
    Callback = function()
        -- Attempt cap
        if S.Attempts >= S.MaxAttempts then
            Notify(
                "🚫  Too Many Attempts",
                "You've used all " .. S.MaxAttempts .. " attempts.\n" ..
                "Please restart the script and try again.",
                6, 4483347087
            )
            return
        end

        local key = Trim(inputKey.Value or "")

        if key == "" then
            lblStatus:Set("Status: ❌  Input is empty — paste your key first.")
            Notify("Empty Key", "Paste your key in the field before validating.", 4, 4483347087)
            return
        end

        lblStatus:Set("Status: ⏳  Checking key...")
        S.Attempts += 1
        if lblAttempts then
            lblAttempts:Set("Attempts used: " .. S.Attempts .. " / " .. S.MaxAttempts)
        end

        local valid, msg = ValidateKey(key)

        if valid then
            SaveKey(key)
            OnUnlock(key, "manual input")
            Notify(
                "🔓  Key Accepted!",
                "Welcome, " .. LP.Name .. "!\n" ..
                "Script Brainrot is now unlocked.",
                8, 4483347087
            )
        else
            lblStatus:Set("Status: ❌  Key rejected.")
            Notify("❌  Invalid Key", msg, 7, 4483347087)
            _G.ScriptBrainrotUnlocked = false
        end
    end,
})

TabKey:CreateDivider()
TabKey:CreateSection("Saved Key")
TabKey:CreateLabel(
    "Your key is saved locally after successful validation.\n" ..
    "It auto-loads next time — no need to paste again today.\n" ..
    "Expired keys (from yesterday) are deleted automatically."
)

lblAttempts = TabKey:CreateLabel("Attempts used: 0 / " .. S.MaxAttempts)

TabKey:CreateButton({
    Name = "🗑️  Delete Saved Key",
    Callback = function()
        DeleteKey()
        S.Unlocked = false
        S.Key = nil
        _G.ScriptBrainrotUnlocked = false
        lblStatus:Set("Status: 🗑️  Saved key cleared. Enter a new key above.")
        Notify("Cleared", "Saved key deleted. Enter a new key to unlock.", 5, 4483347087)
    end,
})

--==============================================================================
-- [11] TAB: SESSION INFO
--==============================================================================

local TabSess = Win:CreateTab("📊  Session", 4483347087)

TabSess:CreateSection("Player Info")
TabSess:CreateLabel("👤  Player:   " .. LP.Name)
TabSess:CreateLabel("🆔  User ID:  " .. tostring(LP.UserId))
TabSess:CreateLabel("📅  Date:     " .. tostring(os.date("%d/%m/%Y")))
TabSess:CreateLabel("⏰  Time:     " .. tostring(os.date("%H:%M:%S")))

TabSess:CreateDivider()
TabSess:CreateSection("Key Status")

lblSession = TabSess:CreateLabel("🔒  No key validated yet this session.")

TabSess:CreateButton({
    Name = "🔄  Refresh Info",
    Callback = function()
        if S.Unlocked and S.Key then
            lblSession:Set(
                "🔓  UNLOCKED\n" ..
                "Player: " .. LP.Name .. "\n" ..
                "Key (last 6): ..." .. S.Key:sub(-6) .. "\n" ..
                "Length: " .. #S.Key .. " chars\n" ..
                "Source: " .. S.Source .. "\n" ..
                "At: " .. os.date("%H:%M:%S", S.ValidatedAt)
            )
        else
            lblSession:Set(
                "🔒  LOCKED\n" ..
                "Go to 🔑 Key System tab to validate your key.\n" ..
                "Attempts: " .. S.Attempts .. " / " .. S.MaxAttempts
            )
        end
    end,
})

TabSess:CreateDivider()
TabSess:CreateSection("About")
TabSess:CreateLabel("Script Brainrot  —  Key System  v3.0.0")
TabSess:CreateLabel("Game:       Tsunami Brainhort (Roblox)")
TabSess:CreateLabel("Author:     ByteBandit_Ofici")
TabSess:CreateLabel("Framework:  Rayfield by Sirius")
TabSess:CreateLabel("Key site:   key-systemz.netlify.app")

TabSess:CreateButton({
    Name = "📋  Copy Key Site URL",
    Callback = function()
        pcall(function() setclipboard(KEY_SITE) end)
        Notify("Copied!", KEY_SITE, 4, 4483347087)
    end,
})

--==============================================================================
-- [12] STARTUP — AUTO-LOAD SAVED KEY
--==============================================================================

task.defer(function()
    task.wait(2.2) -- wait for Rayfield loading animation

    local saved = LoadKey()

    if saved then
        OnUnlock(saved, "auto-saved key")
        Notify(
            "🔓  Auto-Unlocked!",
            "Your key from today was loaded automatically.\n" ..
            "Welcome back, " .. LP.Name .. "!",
            7, 4483347087
        )
    else
        -- No valid saved key — prompt user
        pcall(function() setclipboard(KEY_SITE) end)
        Notify(
            "🔑  Key Required",
            "Get your daily key at:\n" .. KEY_SITE ..
            "\n\nThe link was copied to your clipboard!\n" ..
            "Paste it in your browser to get today's key.",
            12, 4483347087
        )
    end
end)

--==============================================================================
-- [13] CLEANUP ON DISCONNECT
--==============================================================================

LP.AncestryChanged:Connect(function(_, parent)
    if parent == nil then
        S.Unlocked                = false
        S.Key                     = nil
        _G.ScriptBrainrotUnlocked = false
        _G.ScriptBrainrotKey      = nil
    end
end)

--==============================================================================
-- [14] GLOBAL API
-- The main Script Brainrot script integrates like this:
--
--   -- At the top of the main script:
--   if not _G.ScriptBrainrotUnlocked then
--       warn("[Script Brainrot] Run the Key System script first!")
--       return
--   end
--
--   -- Or use the validator directly:
--   local ok, msg = _G.ValidateScriptBrainrotKey(someKey)
--==============================================================================

_G.ValidateScriptBrainrotKey = ValidateKey

if not _G.ScriptBrainrotUnlocked then
    _G.ScriptBrainrotUnlocked = false
end
